### ISSUE TITLE
babel所用的时间 是如何进行配置展示的

### ISSUE THREAD

**Issue by LFdeWeb** [ChhXin/multi-page-dist#1]
看到奇舞周刊 上面 输出了 babel-loader所用的时间  查了好久没有看到怎么 配置展示时间  想问下

**Comment by xinchanghao** [comment]
@LFdeWeb hi，时间统计用的是插件哦，speed-measure-webpack-plugin，安利一波哈哈。https://www.npmjs.com/package/speed-measure-webpack-plugin

**Comment by LFdeWeb** [comment]
十一点半的时候刚找到 thanks

**Comment by LFdeWeb** [comment]
@ChhXin 十一点半的时候刚找到 thanks
